import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.scss";

import LandingPage from "../Components/LandingPage";
import { Camera, FacebookMessanger, MaleUser, User } from "../../public/SVG";
export default function Home() {
  return (
    <>
      <Head>
        <title>Sialo: Your Personal Social Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={`${styles.nav} + h-[60px] flex items-center justify-between px-[4%] fixed w-[100%] top-0 z-50`}>
        <h1 className={`${styles.quickSand} + text-[30px] font-bold leading-[40px]`}>Sialo</h1>

        <section className={`flex gap-[18px]`}>


          <div className={`${styles.svg} + w-[32px] h-[32px] cursor-pointer grid place-items-center rounded-full`}>
            <User />
          </div>

          <div className={`${styles.svg} + w-[32px] h-[32px] cursor-pointer grid place-items-center rounded-full`}>
            <FacebookMessanger />
          </div>
        </section>
      </nav>


      <LandingPage />



    </>
  );
}
