import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.scss";

import LandingPage from "../Components/LandingPage";
import { Camera, FacebookMessanger, MaleUser, User } from "../../public/SVG";
import Navbar from "@/Components/Navbar";
export default function Home() {
  return (
    <>
      <Head>
        <title>Sialo: Your Personal Social Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <LandingPage />



    </>
  );
}
