import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.scss";

import { Camera, FacebookMessanger, User } from "../../public/SVG";
import { MaleUser } from "../../public/SVG";
import LandingPage from "../Components/LandingPage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Xor: Travel Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={`${styles.nav} + h-[60px] flex items-center justify-between px-[4%]`}>
        <h1 className={`${styles.quickSand} + text-[30px] font-bold leading-[40px]`}>Sialo</h1>

        <section className={`flex gap-[18px]`}>

          <div className={`${styles.svg} + w-[32px] h-[32px] cursor-pointer grid place-items-center rounded-full`}>
            <FacebookMessanger />
          </div>

          <div className={`${styles.svg} + w-[32px] h-[32px] cursor-pointer grid place-items-center rounded-full`}>
            <MaleUser />
          </div>

        </section>
      </nav>


      <LandingPage />



    </>
  );
}
